services:
  - type: web
    name: oflc-wage-query
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
